/* 오프라인 실행용 캐시. 배포할 때마다 VERSION을 올리세요. */
const VERSION = 'toema-3.7.2';
const FILES = ['./', 'index.html', 'config.js', 'manifest.json', 'js/data.js', 'js/core.js', 'js/art.js', 'js/audio.js', 'js/rank.js', 'js/app.js', 'js/i18n.js', 'js/i18n_dict.js', 'js/native.js',
  'img/baekho.png', 'img/bari.png', 'img/bat.png', 'img/bear.png', 'img/boar.png', 'img/buffalo.png', 'img/bulga.png', 'img/cheongryong.png', 'img/crow.png', 'img/daesung.png', 'img/dog.png', 'img/fox.png', 'img/gangrim.png', 'img/gildong.png', 'img/haetae.png', 'img/hwaseo.png', 'img/hyeonmu.png', 'img/icon_armor.png', 'img/icon_aura.png', 'img/icon_beads.png', 'img/icon_bell.png', 'img/icon_fan.png', 'img/icon_haste.png', 'img/icon_knives.png', 'img/icon_luck.png', 'img/icon_magnet.png', 'img/icon_might.png', 'img/icon_quake.png', 'img/icon_regen.png', 'img/icon_soulfire.png', 'img/icon_staff.png', 'img/icon_swift.png', 'img/icon_talisman.png', 'img/icon_thunder.png', 'img/icon_vigor.png', 'img/imugi.png', 'img/jujak.png', 'img/seolmun.png', 'img/snake.png', 'img/tiger.png', 'img/uchi.png', 'img/jungyeong.png', 'img/jacheongbi.png', 'img/wolf.png', 'img/m_bat2.png', 'img/m_bear2.png', 'img/m_boar2.png', 'img/m_centi.png', 'img/m_cobra.png', 'img/m_crow2.png', 'img/m_deer.png', 'img/m_fox.png', 'img/m_goat.png', 'img/m_hedgehog.png', 'img/m_jackal.png', 'img/m_lcat.png', 'img/m_otter.png', 'img/m_rabbit.png', 'img/m_rat.png', 'img/m_spider.png', 'img/m_tanuki.png', 'img/m_toad.png', 'img/m_weasel.png', 'img/m_wildcat.png', 'img/item_chest.png', 'img/item_coin.png', 'img/item_bag.png', 'img/item_heal.png', 'img/item_magnet.png', 'img/ground_grass.png', 'img/ground_swamp.png', 'img/ground_snow.png', 'img/ground_ash.png', 'img/ground_sea.png', 'img/ground_night.png', 'img/imugi_head.png', 'img/imugi_roar.png', 'img/imugi_segA.png', 'img/imugi_segB.png', 'img/imugi_tail.png', 'img/cy_head.png', 'img/cy_roar.png', 'img/cy_segA.png', 'img/cy_segB.png', 'img/cy_tail.png', 'img/cheonha.png', 'img/dudu.png', 'img/haemosu.png', 'img/icon_bomb.png', 'img/icon_chain.png', 'img/icon_clone.png', 'img/icon_club.png', 'img/icon_dur.png', 'img/icon_essence.png', 'img/icon_feather.png', 'img/icon_focus.png', 'img/icon_fortune.png', 'img/icon_foxbead.png', 'img/icon_frost.png', 'img/icon_guard.png', 'img/icon_hwacha.png', 'img/icon_hwando.png', 'img/icon_jeung.png', 'img/icon_r_bell.png', 'img/icon_r_bronze.png', 'img/icon_r_coin.png', 'img/icon_r_ginseng.png', 'img/icon_r_hat.png', 'img/icon_r_herb.png', 'img/icon_r_horn.png', 'img/icon_r_jangseung.png', 'img/icon_r_ledger.png', 'img/icon_r_mirror.png', 'img/icon_r_pouch.png', 'img/icon_r_scale.png', 'img/icon_r_shoes.png', 'img/icon_r_sword.png', 'img/icon_r_thread.png', 'img/icon_r_thunder.png', 'img/icon_shield.png', 'img/icon_sinjang.png', 'img/icon_u_bell.png', 'img/icon_u_hwacha.png', 'img/icon_u_quake.png', 'img/icon_u_soul.png', 'img/icon_u_sword.png', 'img/icon_u_thunder.png', 'img/icon_water.png', 'img/musun.png', 'img/seolhwa.png', 'img/yeonho.png', 'icons/icon-192.png'];
self.addEventListener('install', e => { e.waitUntil(caches.open(VERSION).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;   // Supabase 등 외부 요청은 건드리지 않음
  // 네트워크 우선, 실패하면 캐시 (업데이트가 바로 반영되도록)
  e.respondWith(fetch(e.request, { cache: 'no-cache' }).then(r => { const cp = r.clone(); caches.open(VERSION).then(c => c.put(e.request, cp)); return r; }).catch(() => caches.match(e.request)));
});
